### ISSUE TITLE
Disable primitive Restart on Adreno

### ISSUE THREAD

**Issue by Roydenko** [Bankaimaster999/Dolphin-MMJR#26]
I know You aren't going to take more requests but please , the MMJR version works me well and i have perfomance issues with MMJR2 , disabling primitive Adreno Restart in this version shall make the perfomance even better . Sorry , i'm asking without knowing if it's diffucult to implement this compared to the others request You taked.

**Comment by BNKMST999** [comment]
This is already done on the latest MMJR2 versoin

**Comment by Bankaimaster999** [comment]
Firstly you posting this in the wrong place ... since this is MMJR and not MMJR2 (The whole primitive restart fix came from studying the commits from MMJ/MMJR in the first place.)

Secondly; This is already done on the latest MMJR2 version (same as dolphin official) ... from version 15109. 
https://github.com/Bankaimaster999/Dolphin-MMJR2/releases
