### ISSUE TITLE
mmjr problems cause of crashes!

### ISSUE THREAD

**Issue by MiniMasterDRC** [Bankaimaster999/Dolphin-MMJR#27]
I have found the possible problem of crashes and freezing in several games, apparently those errors are implemented by mmj in version 11453 for some reason it does not exist in any version prior to this ... is there any possibility of changing the mmjr code to one older version to fix

I still don't understand why the errors and blockages of this version of mmj that older versions don't have, maybe that's why I removed it from its github...
The games with the most bugs are

1.sonic adventure 2 (freeze)
2.the legend of zelda TP(freeze)
3.lego star wars clone wars(freeze)
4. shadow hedgehod (bugs and crashes)
5.amazing island(crashes)
6,007 nightfire(crashes)
and certain bugs in the controls in certain games that I will not mention

So far I have tried those, all those errors do not exist in any version prior to the one mentioned

I know you are no longer accepting requests but is there any chance to downgrade the code to the problem?
 well I hope your answer thanks in advance and sorry for the inconvenience

**Comment by BNKMST999** [comment]
There is a problem because I am not sure what weihuoya changed from the older versions to 11453. Some games got a performance boost but other much like Sonic Adventure 2, etc. got affected.
I haven't been able to properly figure it out but I believe that its related to the dual core or single core changes. That is one of the issues from weihuoya's build that I have not been able to figure out.

Best to either use MMJR2 or Dolphin Official for those games because chances of me going back to his older versions, compile it and kind of update it while excluding those issues ... that's a bit much to ask for a discontinued project.
