### ISSUE TITLE
mali vulkan fix for lumince mmjr2

### ISSUE THREAD

**Issue by MonkoftheFunk** [Bankaimaster999/Dolphin-MMJR#37]
Hi I just discouvered mmjr and it has the much contested (by dolphin devs) the mali fix (v1.0-11460) for vulkan that works awesome for GC, I know your not doing dev on mmjr and since deleting your old repo I can't find where you made that fix, but is it possible for you to pretty please make a pull request with that change to lumince mmjr2 (I know they are taking a break as well)? AAaaand I see it might be tricky to do with new merged in 5.0 code.... but maybe? (perhaps show what code was changed to make it possible?)
Sorry, tried to contact on discord... but you have it set to disabled (I know for this very reason) and I saw the previous "issue" here about trying to communicate to you or lumince... Buuut thought I'd give it a try 😬 and thanks again for all the scoped storage stuff, that has been a headache for all devs/users lately <3

https://bugs.dolphin-emu.org/issues/10072
https://github.com/dolphin-emu/dolphin/pull/4577

**Comment by Bankaimaster999** [comment]
I can't say much on Lumince version since he disabled issues and is also taking a break. If I got time I'd do that but I got other things I'm working on so you might just end up seeing one version of MMJR going forward (working on getting another dev to work with me instead)
Though I will keep this post in mind going forward if I get the time.
