### ISSUE TITLE
Joystick controls just don't go that way you want - Pokemon XD: Gale Of Darkness

### ISSUE THREAD

**Issue by mstudio45** [Bankaimaster999/Dolphin-MMJR#8]
Hi there,
I just played Pokemon XD: Gale Of Darkness but then the joystick just don't want to listen and goes by it self.
Here is a video:
https://streamable.com/0hnbc5
I'm using latest (11461) version of Dolphin |MMJR|.

**Comment by Bankaimaster999** [comment]
I can't tell what the issue is considering that in the video the controls work unless you got to a certain area ... in addition to that I haven't changed anything related to the analog controls or input controls at all.

What you can do to test this is try Dolphin MMJ 11453 (https://www.mediafire.com/file/xiy94vdrc4yjh61/Dolphin_5.0-11453_%2528MMJ%2529.apk/file) and see if it also has this problem (save states should work across). If the controls have the same issue then the issue is from the original source code from MMJ.

**Comment by mstudio45** [comment]
Hi there,

i tested the joystick in every area i have unlocked in the Pokemon XD: Gale Od Darkness and it does only on some certain parts.
I tested some other games and works fine.
Im sorry that i didnt use general. It wont happened again.
The issue is okay, it wont happening so much time now.

Thank you for respone and goodbye.
